### ISSUE TITLE
Can we pass configuration from the controller?

### ISSUE THREAD

**Issue by bilalsaeed** [hmartos/angular-reservation#10]
Hi,

I am stuck at one point where I need to pass the configuration from controller?

Is it possible to do that with existing plugin or do I have to make a provider?

Best,

**Comment by hmartos** [comment]
Hi @bilalsaeed,

I have just published a new release 0.6.0 with the possibility to pass the configuration from a controller.

You should be able to do something like this:

```html
<reservation config="myCtrl.config"></reservation>
```

And the config passed will override the configuration of the provider.

You can find the default configuration object [here](https://github.com/hmartos/angular-reservation/blob/master/src/js/config.js).

Let me know if this solves your issue.

Thanks!

**Comment by bilalsaeed** [comment]
Works like a charm.

Thank you so much for your help. :)
