### ISSUE TITLE
bower.json "main" property  breaking my Grunt build process

### ISSUE THREAD

**Issue by stanica** [hmartos/angular-reservation#3]
My current build process looks at the "main" property of bower.json in each module and automatically includes those files in `index.html`. Since `app.js` isn't enough to run your module I've temporarily modified the property to be: `"main": ["dist/angular-reservation.min.js", "dist/angular-reservation.min.css"]`

Are you able to modify it like this?

**Comment by hmartos** [comment]
I sincerely forgot about this attribute when creating the module, thanks!

After a bit of research in the [bower documentation](https://github.com/bower/spec/blob/master/json.md#main) I have added the non-minifed distribution files instead of the minified ones, did this suits for you??

**Comment by stanica** [comment]
That works! Thanks a lot!

**Comment by hmartos** [comment]
You are welcome!
