### ISSUE TITLE
way to select available date?

### ISSUE THREAD

**Issue by rob1nxu** [hmartos/angular-reservation#4]
Hi, thank you for making this module and the effot! 

Would like to ask if there is a way to get available dates too? (Not just available hours). 

This is for a scenario whereby a user would like to set his available date and hours for the other party to make a reservation.

**Comment by hmartos** [comment]
Hi @rob1nxu, thank you very much for using it, I think this could be a great feature for this module!. 

I am thinking about a **configuration option to enable/disable load of available dates** (which should be _false_ by default to maintain compatibility with previous versions) and another **configuration option to setup the API URL to GET the list of available dates**.

In that way, if you configure the module with the first option set to _true_ and the second set to _http://localhost:8080/availableDates_, the first thing the module will do is to send an HTTP GET request to _http://localhost:8080/availableDates_ (showing loader while request is not finished) and pass the response of this request to the datepicker options, allowing you to pass available dates to the datepicker.

A few questions more should be done, but first of all, will this fill your requirements?

**Comment by hmartos** [comment]
Finally, I added this functionality to the module. The new configuration options are called **getAvailableDatesFromAPI** and **getAvailableDatesAPIUrl**.

These configuration options are added to the [documentation](https://hmartos.github.io/angular-reservation/#!#docs) in **Configuration options** section and the API documentation for the new HTTP request can be found [here](https://github.com/hmartos/angular-reservation/blob/master/APIDocs.md).
