### ISSUE TITLE
help with install

### ISSUE THREAD

**Issue by AJAYSFencing** [hmartos/angular-reservation#6]
Hi,
Thx so much for putting this together.
I'm a website designer/developer and want to use your code for part of a sales pitch to a potential client.
Whilst i'm adept with HTML, my expertise ends there!
Do you have any basic instructions other than already provided that may help a newbie!
Cheers, Andy
Melbourne, Australia

**Comment by hmartos** [comment]
Hi @AJAYSFencing! Thank you very much for your interest in this module!

If you want to use this reservation system **you will need both a Frontend part and a Backend part**.

**The Frontend part is an AngularJS module** to set up an appointment in a calendar like shown in the [DEMO](https://hmartos.github.io/angular-reservation/#!#demo). The documentation of this module is available [here](https://hmartos.github.io/angular-reservation/#!#docs) and I think it should be enough to set up the module inside an AngularJS web-app. If you need help with the installation of this module, you can open a specific issue.

**The AngularJS module just makes requests to a REST API according to this [specification](https://github.com/hmartos/angular-reservation/blob/master/APIDocs.md).** 

**The Backend part should handle these reservations in a persistent database.** This can be implemented using different languages and databases. [Here](https://github.com/hmartos/angular-reservation-api) there is a simple example of a NodeJS Restful API that uses MongoDB to store reservations. Although it can be a good starting point, it's not a production-ready artifact. I was thinking of making a Docker container that put these things together, but I don't have much free time.

If you have further questions don't hesitate to contact me at hectormartosg@gmail.com

Cheers!

Héctor
