### ISSUE TITLE
AngularJS to Angular

### ISSUE THREAD

**Issue by empasca** [hmartos/angular-reservation#7]
Hey guys! I am new to Angular and AngularJS. Is it hard to convert this module from AngularJS to Angular? Can you help me out?

**Comment by hmartos** [comment]
I thought about it but it would be a completely different module and I have no intention of developing it by the moment.

Sorry.

**Comment by hmartos** [comment]
If you want to try to convert it yourself, you can follow this oficial guidelines:

https://angular.io/guide/upgrade

But I think it will require a full rewrite

**Comment by Johnowen043** [comment]
Hy sir, do you have video tutorial for this project?

**Comment by hmartos** [comment]
I’m afraid I don’t, sorry, but maybe Google can help you with that

https://www.google.es/search?tbm=vid&q=migrate+angularjs+to+angular+video+tutorial

**Comment by Johnowen043** [comment]
Thank you sir
