### ISSUE TITLE
Video tutorial 

### ISSUE THREAD

**Issue by Johnowen043** [hmartos/angular-reservation#8]
Do you have video tutorial for this?

**Comment by hmartos** [comment]
I’m afraid I don’t, sorry, but maybe Google can help you with that:

https://www.google.es/search?tbm=vid&q=migrate+angularjs+to+angular+video+tutorial

**Comment by Johnowen043** [comment]
How to make like your app demo, my calendar dont show, sorry im newbie for
angularjs

**Comment by hmartos** [comment]
You can check the gh-pages branch which contains the code for the example:

https://github.com/hmartos/angular-reservation/tree/gh-pages?files=1

Take a look at the scripts loaded in index.html file to embed the module in a simple HTML page:

https://github.com/hmartos/angular-reservation/blob/gh-pages/index.html

**Comment by Johnowen043** [comment]
thank you so much sir

Pada tanggal Jum, 21 Feb 2020 pukul 14.58 hmartos <notifications@github.com>
menulis:

**Comment by hmartos** [comment]
You’re welcome!
