### ISSUE TITLE
any solution for jQuery v3.2.0

### ISSUE THREAD

**Issue by bilalsaeed** [hmartos/angular-reservation#9]
Hi,

It does not seem to work with jQuery v3.2.0. Is there anyway I can make it work with jQuery v3.2.0?

Any help will be highly appreciated. 

thank you.

**Comment by hmartos** [comment]
Hi @bilalsaeed, 

In fact, jQuery is not required for this module, but for `bootstrap.min.js`, so maybe you can check which version of Bootstrap you are using. I'm using v3.3.7 on the Demo page.

Anyway, I have pushed a new version of the Demo with jQuery 3.2.0 so you can check it out.
[Demo](https://hmartos.github.io/angular-reservation/)
[Demo Source Code](https://github.com/hmartos/angular-reservation/tree/gh-pages)

I hope this helps you.

Thank you very much!

**Comment by bilalsaeed** [comment]
Hi @hmartos ,

Thank you for prompt response.

I am using Bootstrap v4.2.1.

I commented out the line [e.determinePreferredLanguage()](url) in **hm.reservation** module, and now it's working.

**Comment by hmartos** [comment]
This line is in charge of the [language negotiation](https://angular-translate.github.io/docs/#/guide/09_language-negotiation) to show the preferred language.

This is an old module and its dependencies are totally outdated, so maybe there is some incompatibility with the required version of the [angular-translate](https://github.com/angular-translate/angular-translate) module.

Anyway, I'm glad that you could make it work.

If you have further problems just let me know and I will try to help you.
